name: CapturetheFlag
version: 1.0-SNAPSHOT
main: me.yoursole.ctf.CTF
api-version: 1.17
commands:
  start:
    description: Start Game
    usage: /<command>
  stop:
    description: Stop Game
    usage: /<command>